In [ ]:
import pandas as pd
import sqlite3
import numpy as np

In [3]:
import sys
sys.path.append("../module/")
from lipinski import *

In [1]:
from rdkit import Chem
# To add a new cell, type '# %%'
# To add a new markdown cell, type '# %% [markdown]'
# %%
import pandas as pd
import sqlite3
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn.cluster import KMeans
from sklearn import preprocessing

from matplotlib import pyplot as ptl
import seaborn as sns
import sys, os
from rdkit import Chem
from rdkit.Chem import Crippen
from rdkit.Chem import Lipinski
from rdkit.Chem import Descriptors
from rdkit.Chem.QED import properties

import subprocess
import threading
import queue

In [4]:
con = sqlite3.connect(f"../data/propriedades.db")
dataframe = pd.read_sql('select * from dados', con)
dataframe

,chembl_id,mw_freebase,alogp,psa,rtb,cx_most_apka,cx_most_bpka,cx_logp,cx_logd,molecular_species,full_mwt,aromatic_rings,heavy_atoms,qed_weighted,mw_monoisotopic,hba_lipinski,hbd_lipinski,num_lipinski_ro5_violations,canonical_smiles
0,CHEMBL18807,660.680,1.8955,220.46,14.0,3.58,NaN,2.15,-4.28,ACID,660.68,4.0,48.0,0.13,660.2431,8.0,7.0,2.0000,C[C@H](NC(=O)[C@H](Cc1ccc(O)cc1)NC(=O)[C@H](C)...
1,CHEMBL19228,479.621,5.0354,56.41,7.0,NaN,7.97,4.99,4.32,NEUTRAL,479.62,5.0,34.0,0.40,479.2043,3.0,1.0,1.0000,CN(CCN1CCC(Cc2c[nH]c3ccc(F)cc23)CC1)S(=O)(=O)c...
2,CHEMBL19051,461.562,4.8437,56.41,5.0,NaN,7.40,4.43,4.13,NEUTRAL,461.56,6.0,33.0,0.43,461.1573,3.0,1.0,0.0000,O=S1(=O)c2cccc3cccc(c23)N1CCN1CC=C(Cc2c[nH]c3c...
3,CHEMBL278743,348.495,1.7873,118.63,8.0,NaN,NaN,NaN,NaN,None,348.50,3.0,NaN,NaN,348.2638,5.0,4.0,0.0000,NCCc1c[nH]cn1.N[C@H](COCC1CCCCC1)Cc1c[nH]cn1
4,CHEMBL19338,381.563,6.6072,3.24,7.0,NaN,8.83,6.92,5.48,BASE,381.56,4.0,29.0,0.42,381.2456,1.0,0.0,1.0000,c1ccc(CCCCN2CCC(=C(c3ccccc3)c3ccccc3)CC2)cc1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2084583,CHEMBL4651241,386.450,2.4600,111.05,7.0,9.12,9.76,1.37,0.08,BASE,386.45,2.0,28.0,0.50,386.1842,7.0,5.0,0.0,CC(C)(CCc1cccc(O)c1)NCC(O)c1cc(O)cc2c1OCC(=O)N2
2084584,CHEMBL4651243,446.550,4.3500,90.82,8.0,9.19,9.98,3.17,1.75,BASE,446.55,3.0,33.0,0.41,446.2206,6.0,4.0,0.0,CC(C)(CC(c1ccccc1)c1ccccc1)NC[C@H](O)c1cc(O)cc...
2084585,CHEMBL4651249,492.640,5.0200,86.74,5.0,9.76,9.13,2.81,1.49,BASE,492.64,3.0,36.0,0.38,492.2857,7.0,4.0,1.0,CC[C@H]1C[N@+]2(O)CCc3cc(OC)c(OC)cc3[C@@H]2C[C...
2084586,CHEMBL4651252,356.420,2.2900,90.82,7.0,9.18,9.79,1.64,0.31,BASE,356.42,2.0,26.0,0.57,356.1736,6.0,4.0,0.0,Cc1ccc(CCCNCC(O)c2cc(O)cc3c2OCC(=O)N3)cc1
2084587,CHEMBL4651254,482.530,4.6300,90.82,8.0,9.19,9.99,3.45,2.04,BASE,482.53,3.0,35.0,0.38,482.2017,6.0,4.0,0.0,CC(C)(CC(c1ccc(F)cc1)c1ccc(F)cc1)NC[C@H](O)c1c...

In [6]:
teste = dataframe['canonical_smiles']

In [7]:
x = teste.to_numpy().tolist()

In [ ]:
def ver_lip(x, i):
    file = open(f"smiles_erro_log_{i}.log",'a')
    for smiles in x:
        try:
            verifica_lipinski(smiles)
        except:
            file.write(f"{smiles}\n")
    file.close()

RDKit WARNING: [15:33:42] WARNING: not removing hydrogen atom without neighbors
[15:33:42] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [15:33:42] WARNING: not removing hydrogen atom without neighbors
[15:33:42] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [15:34:25] WARNING: not removing hydrogen atom without neighbors
[15:34:25] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [15:34:25] WARNING: not removing hydrogen atom without neighbors
[15:34:25] WARNING: not removing hydrogen atom without neighbors

In [ ]:
def verifica_kuku(array, threads_num):
  jobs = np.array_split(array, threads_num)
  processos = []    
  for i in range(1, threads_num):
    processThread = threading.Thread(target=ver_lip, args=(job.pop(), i))
    processThread.start()
    processos.append(processThread)
  ver_lip(job.pop(), 0)
  for proc in processos:
    proc.join()

In [ ]:
verifica_kuku(x,20)